### ISSUE TITLE
nlopt error while installing package with catkin_make

### ISSUE THREAD

**Issue by akmandor** [VladyslavUsenko/ewok#11]
I am getting the following error while trying to install the package.

![catkin_make_ewok_nlopt_error](https://user-images.githubusercontent.com/6059466/66243253-ea010700-e6d1-11e9-9b9c-0de57f5de27a.png)

(As I know) I have already installed nlopt successfully (because I used it before but not touched for a while). I would be happy if you could guide me to fix this issue and install the package. Thanks.

**Comment by VladyslavUsenko** [comment]
It looks like you have 2 versions of nlopt installed. One in `/usr/include/nlopt.hpp` (from apt-get) and another one in `/usr/local/include/nlopt.hpp`. The easiest solution would be to delete the last one, clean the workspace and recompile.

**Comment by akmandor** [comment]
Thank you for your fast and accurate response. Now I can run the simulation.
