### ISSUE TITLE
Quick question about ring buffer

### ISSUE THREAD

**Issue by haritsahm** [VladyslavUsenko/ewok#12]
Hi! I'm trying to plan a path using RRT with your ring buffer. But I'm not sure how to get the minimum and maximum voxel position to generate random location of the nodes. This is my code, am I doing it right? Thank you!

```cpp
        Vector3 point_min, point_max, rand_point, center_point;
        Vector3i point_idx, center_idx;

        occupancy_buffer_.getVolumeMinMax(point_min, point_max);
        center_idx = occupancy_buffer_.getVolumeCenter();
        occupancy_buffer_.getPoint(center_idx, center_point);
```

**Comment by lknnnli** [comment]
Hi, hello, May I ask a question, I'm currently looking into this project, and I need some help.

do you know how they generate the initial global trajectory(the pink one)? and where they save the initial world with this pink global trajectory?

Many thanks for your kind help in advance.

**Comment by haritsahm** [comment]
The system use Polynomial3DOptimization, check the example on how to use it [trajectory_replanning_example.cpp#L306](https://github.com/VladyslavUsenko/ewok/blob/e115df0427903d719f9b16d8811957b3b46df248/ewok_simulation/src/trajectory_replanning_example.cpp#L306)
