### ISSUE TITLE
what is the meaning of these parameters?

### ISSUE THREAD

**Issue by dssdyx** [VladyslavUsenko/ewok#14]
In code, there are some parameters such as num_opt_points, dt, distance_threshold and so on. I changed some of them. For example , dt, when I changed it, 0.5->1, or 0.5 ->0.25, the line became very weird, no smooth with many turning points. So, what's the meaning of them and how can i adjust them?

**Comment by dvdmc** [comment]
I'm not related to the authors of the paper (just working on a student project) but the meaning of the parameters are specified in the paper as: num_opt_points = C (in section 5.E), dt =  delta t (section 3.A) and distance_threshold = tau (in section 5.B equation 18)
