### ISSUE TITLE
Ring buffer quick question

### ISSUE THREAD

**Issue by szebedy** [VladyslavUsenko/ewok#6]
Hi Vladyslav,

First of all, great work! I am trying to use this repo for collision avoidance with a delivery drone. All is working fine except the ring buffer. I am suspecting that the image processing part is not working.

May I ask why you divide the depth value by 5000?

https://github.com/VladyslavUsenko/ewok/blob/master/ewok_ring_buffer/src/tum_rgbd_ring_buffer_example.cpp#L141

**Comment by VladyslavUsenko** [comment]
This is specific to the TUM RGB-D dataset file format (https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats):

The depth images are scaled by a factor of 5000, i.e., a pixel value of 5000 in the depth image corresponds to a distance of 1 meter from the camera, 10000 to 2 meter distance, etc. A pixel value of 0 means missing value/no data.

**Comment by szebedy** [comment]
Thanks for the quick reply!
