### ISSUE TITLE
Circular Buffer vs Octomap benchmarking running not ok

### ISSUE THREAD

**Issue by jeannotes** [VladyslavUsenko/ewok#7]
Hi, I just follow your steps in readme running "Circular Buffer vs Octomap benchmarking", now the phenomenon is like: after I type "./benchmark.py", no message output,so I want to type in "ctrl+c" to terminate this program, now start log some output(debugging message), however, there is no message out.
why is that?

**Comment by VladyslavUsenko** [comment]
Might be related to #9. If not fixed, reopen.
