### ISSUE TITLE
benchmark.py   slam file location changed

### ISSUE THREAD

**Issue by patrickpoirier51** [VladyslavUsenko/ewok#9]
https://github.com/VladyslavUsenko/ewok/blob/master/ewok_ring_buffer/benchmarking/benchmark.py#L11

dataset_url = 'http://filecremers3.informatik.tu-muenchen.de/rgbd/dataset/freiburg2/rgbd_dataset_freiburg2_pioneer_slam.tgz'

file location change to:
https://vision.in.tum.de/rgbd/dataset/freiburg2/rgbd_dataset_freiburg2_pioneer_slam.tgz

**Comment by VladyslavUsenko** [comment]
Thanks! I've changed it.
